[workspace]
members = [
  "neqo-client",
  "neqo-common",
  "neqo-crypto",
  "neqo-http3",
  "neqo-http3-client",
  "neqo-http3-server",
  "neqo-qpack",
  "neqo-server",
  "neqo-transport",
  "neqo-interop",
]
