# FlowShaper configs

[debug]
  initial_md = 3000
  rx_stream_data_window = 1048576
  local_md = 4611686018427387903
  dummy_size = 700
  dummy_nc = 900
  dummy_ns = 1200
  dummy_maxw = 2.5
  dummy_minw = 0.1

[t1]
  initial_md = 3000
  rx_stream_data_window = 1048576
  local_md = 4611686018427387903
  dummy_size = 1400
  dummy_nc = 1700
  dummy_ns = 1700
  dummy_maxw = 14.0
  dummy_minw = 1.0