[package]
name = "neqo-crypto"
version = "0.1.0"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2018"
build = "build.rs"

[dependencies]
neqo-common = { path = "../neqo-common" }
log = "0.4.0"

[build-dependencies]
bindgen = "0.46"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
